// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD36TJlQCKXJbbXqdb4Y17VF13poHiLHig',
    appId: '1:950044072953:web:8763985d91b7db316fbb28',
    messagingSenderId: '950044072953',
    projectId: 'tripit-267d5',
    authDomain: 'tripit-267d5.firebaseapp.com',
    storageBucket: 'tripit-267d5.appspot.com',
    measurementId: 'G-ZS418K741M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmSgIoYFLO0AqjkNhnG8R2EYhVi26qpk8',
    appId: '1:950044072953:android:34a3fdddcc11cdf16fbb28',
    messagingSenderId: '950044072953',
    projectId: 'tripit-267d5',
    storageBucket: 'tripit-267d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7C_sjnWSzwuZquNNvFuoee1nElcdsSdw',
    appId: '1:950044072953:ios:1480fe08d9f5bbae6fbb28',
    messagingSenderId: '950044072953',
    projectId: 'tripit-267d5',
    storageBucket: 'tripit-267d5.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7C_sjnWSzwuZquNNvFuoee1nElcdsSdw',
    appId: '1:950044072953:ios:1480fe08d9f5bbae6fbb28',
    messagingSenderId: '950044072953',
    projectId: 'tripit-267d5',
    storageBucket: 'tripit-267d5.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD36TJlQCKXJbbXqdb4Y17VF13poHiLHig',
    appId: '1:950044072953:web:90b05d6817421cc66fbb28',
    messagingSenderId: '950044072953',
    projectId: 'tripit-267d5',
    authDomain: 'tripit-267d5.firebaseapp.com',
    storageBucket: 'tripit-267d5.appspot.com',
    measurementId: 'G-VR1Z335Q4C',
  );
}
